#!/usr/bin/env -S deno run --allow-all
/**
 * Deno build script for opencode
 *
 * This script compiles opencode for various platforms using Deno's compile feature.
 * It's an alternative to the Bun build script for better Windows stability.
 *
 * Usage:
 *   deno run --allow-all script/build-deno.ts [--single] [--target=<target>]
 *
 * Options:
 *   --single    Build only for the current platform
 *   --target    Specific target (e.g., x86_64-pc-windows-msvc)
 */

import * as path from "https://deno.land/std@0.224.0/path/mod.ts"
import { ensureDir } from "https://deno.land/std@0.224.0/fs/mod.ts"

const __dirname = path.dirname(path.fromFileUrl(import.meta.url))
const projectDir = path.resolve(__dirname, "..")

// Read package.json for version
const pkgJson = JSON.parse(await Deno.readTextFile(path.join(projectDir, "package.json")))
const version = pkgJson.version as string

// Deno compile targets
// Format: https://deno.land/manual/tools/compiler#cross-compilation
const allTargets = [
  { target: "x86_64-unknown-linux-gnu", os: "linux", arch: "x64" },
  { target: "aarch64-unknown-linux-gnu", os: "linux", arch: "arm64" },
  { target: "x86_64-pc-windows-msvc", os: "windows", arch: "x64" },
  // Note: Windows ARM64 is not yet supported by Deno compile
  { target: "x86_64-apple-darwin", os: "darwin", arch: "x64" },
  { target: "aarch64-apple-darwin", os: "darwin", arch: "arm64" },
]

// Parse command line arguments
const args = Deno.args
const singleFlag = args.includes("--single")
const targetArg = args.find((a) => a.startsWith("--target="))?.split("=")[1]

// Filter targets based on flags
let targets = allTargets
if (targetArg) {
  targets = allTargets.filter((t) => t.target === targetArg)
} else if (singleFlag) {
  const currentOs = Deno.build.os
  const currentArch = Deno.build.arch
  targets = allTargets.filter((t) => {
    const osMatch =
      (currentOs === "windows" && t.os === "windows") ||
      (currentOs === "darwin" && t.os === "darwin") ||
      (currentOs === "linux" && t.os === "linux")
    const archMatch =
      (currentArch === "x86_64" && t.arch === "x64") || (currentArch === "aarch64" && t.arch === "arm64")
    return osMatch && archMatch
  })
}

if (targets.length === 0) {
  console.error("No matching targets found")
  Deno.exit(1)
}

console.log(`Building opencode v${version}`)
console.log(`Targets: ${targets.map((t) => t.target).join(", ")}`)

// Clean dist directory
const distDir = path.join(projectDir, "dist-deno")
try {
  await Deno.remove(distDir, { recursive: true })
} catch {
  // Ignore if doesn't exist
}
await ensureDir(distDir)

// Fetch and generate models snapshot (similar to Bun build)
const modelsUrl = Deno.env.get("OPENCODE_MODELS_URL") || "https://models.dev"
const modelsJsonPath = Deno.env.get("MODELS_DEV_API_JSON")
let modelsData: string
if (modelsJsonPath) {
  modelsData = await Deno.readTextFile(modelsJsonPath)
} else {
  const response = await fetch(`${modelsUrl}/api.json`)
  modelsData = await response.text()
}
await Deno.writeTextFile(
  path.join(projectDir, "src/provider/models-snapshot.ts"),
  `// Auto-generated by build-deno.ts - do not edit\nexport const snapshot = ${modelsData} as const\n`,
)
console.log("Generated models-snapshot.ts")

// Build for each target
for (const { target, os, arch } of targets) {
  const name = `opencode-${os}-${arch}`
  const outputDir = path.join(distDir, name, "bin")
  await ensureDir(outputDir)

  const outputFile = os === "windows" ? path.join(outputDir, "opencode.exe") : path.join(outputDir, "opencode")

  console.log(`\nBuilding ${name} (${target})...`)

  // Note: Deno compile requires a Deno-compatible entry point
  // We need to create a Deno shim that imports the main module
  const entryPoint = path.join(projectDir, "src/deno-entry.ts")

  // Build compile command
  const cmd = new Deno.Command("deno", {
    args: [
      "compile",
      "--allow-all", // Grant all permissions
      "--target",
      target,
      "--output",
      outputFile,
      // Deno-specific environment variables
      "--env",
      `OPENCODE_VERSION=${version}`,
      entryPoint,
    ],
    cwd: projectDir,
    stdout: "inherit",
    stderr: "inherit",
  })

  const result = await cmd.output()

  if (!result.success) {
    console.error(`Failed to build ${name}`)
    continue
  }

  // Write package.json for npm distribution
  await Deno.writeTextFile(
    path.join(distDir, name, "package.json"),
    JSON.stringify(
      {
        name,
        version,
        os: [os],
        cpu: [arch],
        runtime: "deno",
      },
      null,
      2,
    ),
  )

  console.log(`✓ Built ${name}`)
}

console.log("\nBuild complete!")
console.log(`Output: ${distDir}`)
